### ISSUE TITLE
'ModelPatcher' object has no attribute 'attachments'

### ISSUE THREAD

**Issue by vu0tran** [bananasss00/ComfyUI_bitsandbytes_NF4-Lora#4]
Getting this error. Any thoughts?

```
!!! Exception during processing !!! 'ModelPatcher' object has no attribute 'attachments'

Traceback (most recent call last):

  File "/workspace/ComfyUI/[execution.py](http://execution.py/)", line 323, in execute

    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/workspace/ComfyUI/[execution.py](http://execution.py/)", line 198, in get_output_data

    return_values = mapnode_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/workspace/ComfyUI/[execution.py](http://execution.py/)", line 169, in mapnode_over_list

    process_inputs(input_dict, i)

  File "/workspace/ComfyUI/[execution.py](http://execution.py/)", line 158, in process_inputs

    results.append(getattr(obj, func)(**inputs))

  File "/workspace/ComfyUI/custom_nodes/ComfyUI_bitsandbytes_NF4-Lora/__init__.py", line 646, in load_checkpoint

    model = NF4ModelPatcher.clone(model)

  File "/workspace/ComfyUI/custom_nodes/ComfyUI_bitsandbytes_NF4-Lora/__init__.py", line 509, in clone

    for k in self.attachments:

AttributeError: 'ModelPatcher' object has no attribute 'attachments'
```

**Comment by vu0tran** [comment]
Updated my ComfyUI and the problem was resolved
